---
# tasks file for redmine
- name: Update APT cache
  apt: update_cache=yes cache_valid_time=9600

- name: Install redmine
  apt: "pkg={{item}} state=latest force=yes update_cache=yes"
  with_items:
    - redmine

- name: iptables -I INPUT -p tcp --dport 3000 -j ACCEPT
  command: iptables -I INPUT -p tcp --dport 3000 -j ACCEPT

- name: iptables-save
  command: iptables-save

- name: add auto start
  command: sudo /bin/sed -i "\$i cd /usr/share/redmine && rails s -b0.0.0.0 -p3000 &" /etc/rc.local
